### ISSUE TITLE
deciding what to do.

### ISSUE THREAD

**Issue by baovuong** [golayalgorithm/hi#1]
yo, we should talk about what to do meng. @rakkaus

**Comment by paivankakkara** [comment]
hey.  We I'll see if there's a time to meet up on this weekend.  But what's
taking up a lot of time right now is trying to get this video sorted out.
We'll try to get this done soon though.  I will be spending most all
tonight on the video and then I've got some school work to prepare for on
saturday and sunday.  I think I'll have some time on sunday though.

On Fri, Feb 13, 2015 at 2:46 AM, Bao Vuong notifications@github.com wrote:

> yo, we should talk about what to do meng. @rakkaus
> https://github.com/rakkaus
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/golayalgorithm/hi/issues/1.

## 

Eric Burns
Chemistry Bachelors of Science
College of Sciences North Carolina State University

**Comment by paivankakkara** [comment]
First we'll approach the basics:
Version 1.

Program graphs all txt file data in current directory.

Version 2. 

Program graphs all txt, csv, xlsx, ascii data in current directory

Version 3. 

Program identifies possible datanames and dataset titles in set of files in current directory.  
Program graphs all data and labels data accordingly (separate graphs)

Version 4. 

Program incorporates a user search through discovered dataset titles to discover the exact files user wants to graph.
Program will tab-autocomplete user queries.
Program graphs user queries. (separate graphs)

Version 5. 

Program may accept multiple user queries at once (i.e. dataset1 dataset25 dataset19)
Program saves queries and loops for all possible data to graph. (separate graphs)

Version 6. 

Program accepts option for graphing all graph data on same graph or separately.

Version 7. 

Graph data may be clicked and highlighted and deleted.

Version 8. 

Graph data deleted may be recovered with ctrl z/cmnd z (only one iteration)

Version 9. 

parallel GUI version of current software

Version 10. 

All annotations (titles, notes, keys, graph data) in graph interphase may autofit within graph interphase window when window is double clicked.

**Comment by baovuong** [comment]
cool, going to put this into separate milestone entries.

**Comment by paivankakkara** [comment]
Awesome!!

On Tue, May 10, 2016 at 1:14 AM, Bao Vuong notifications@github.com wrote:

> Closed #1 https://github.com/golayalgorithm/hi/issues/1.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/golayalgorithm/hi/issues/1#event-655123895

## 

Eric Burns
B.S. Chemistry at North Carolina State University
Durrant Lab Imperial College London
MRes Graduate Researcher
